# Sklearn

## sklearn.cross_validation

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [1]:
from sklearn import cross_validation, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [2]:
iris = datasets.load_iris()

In [3]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [4]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [6]:
print('Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data), len(test_data)))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [7]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-7-366f8cb9ba1c>, line 1)

In [ ]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

### Стратегии проведения кросс-валидации

#### KFold

In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 5):
    print train_indices, test_indices

In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True):
    print train_indices, test_indices

In [ ]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

#### StratifiedKFold

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print train_indices, test_indices

In [ ]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print train_indices, test_indices

#### ShuffleSplit

In [12]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 3):
    print (train_indices, test_indices)

[2 4 1 0 8 5 3] [6 9 7]
[9 0 6 2 4 3 7] [8 5 1]
[5 1 9 0 8 2 4] [6 3 7]
[9 6 8 3 0 4 7] [1 5 2]
[6 8 2 4 9 0 1] [5 7 3]
[3 7 2 1 4 0 8] [6 5 9]
[3 7 5 6 9 8 1] [2 4 0]
[9 7 3 6 1 5 0] [8 2 4]
[1 4 3 5 9 7 0] [2 8 6]
[5 8 7 4 3 0 2] [6 1 9]


#### StratifiedShuffleSplit

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

#### Leave-One-Out

In [ ]:
for train_indices, test_index in cross_validation.LeaveOneOut(10):
    print train_indices, test_index

Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators